name: Patch vulnerable images

on:
  push:
    branches:
      - main
    paths-ignore:
      - '**.md'
  workflow_dispatch:

permissions:
  contents: read
  packages: write

jobs:
  patch:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      #max-parallel: 2
      matrix:
        images:
          - "ghcr.io/aquasecurity/trivy-operator:0.16.1"
          - "quay.io/k8slens/bored-agent:0.12.8"
          - "quay.io/k8slens/recurly-api-proxy:0.5.3"
          - "gcr.io/distroless/cc-debian10"
    steps:
      # 1. Trivy scan for OS-level vulnerabilities
      - name: Generate Trivy Report
        uses: aquasecurity/trivy-action@d43c1f16c00cfd3978dde6c07f4bbcf9eb6993ca
        with:
          scan-type: "image"
          format: "json"
          output: "report.json"
          ignore-unfixed: true
          vuln-type: "os"
          image-ref: ${{ matrix.images }}
          
      # 2. Extract CVE, Severity, and Title from Trivy's report.json
      - name: Extract CVEs from Trivy Report
        run: |
          echo "=== Extracting OS-level CVEs from Trivy report ==="
          jq -r '
            (.Results? // [])
            | map(select(.Class == "os-pkgs" and .Vulnerabilities != null))
            | .[]
            | .Vulnerabilities[]?
            | "CVE: \(.VulnerabilityID // "N/A"), Severity: \(.Severity // "N/A"), Title: \(.Title // "N/A")"
          ' report.json > cves_report.txt

          echo "Contents of cves_report.txt:"
          cat cves_report.txt

      # 3. Check vulnerability count for fixable vulns
      - name: Check vulnerability count
        id: vuln_count
        run: |
          report_file="report.json"
          vuln_count=$(jq 'if .Results then [
              .Results[]
              | select(.Class=="os-pkgs" and .Vulnerabilities!=null)
              | .Vulnerabilities[]
              | select(.Status=="fixed")
            ] | length else 0 end' "$report_file")

          echo "Detected $vuln_count *fixable* OS vulnerabilities in ${{ matrix.images }}"
          echo "vuln_count=$vuln_count" >> $GITHUB_OUTPUT

      # 4. Patch (COPA) if fixable vulnerabilities exist
      - name: Run Copa action
        if: steps.vuln_count.outputs.vuln_count != '0'
        id: copa
        uses: project-copacetic/copa-action@main
        with:
          image: ${{ matrix.images }}
          image-report: "report.json"
          patched-tag: "patched"
          timeout: "5m"
          output: vex.json
          format: "openvex"

      # 5. Log in to GHCR if COPA ran
      - name: Login to GHCR
        if: steps.copa.conclusion == 'success'
        id: login
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # 6. Push patched image to GHCR
      - name: Push patched image
        if: steps.login.conclusion == 'success'
        run: |
          # Sanitize the matrix.images name so it can be used in a Docker tag
          SANITIZED_TAG=$(echo "${{ matrix.images }}" | tr '/:' '-')
          REPO_OWNER="${{ github.repository_owner }}"
          FINAL_IMAGE="ghcr.io/${REPO_OWNER}/copa-patched:${SANITIZED_TAG}"

          echo "Retagging ${{ steps.copa.outputs.patched-image }} => $FINAL_IMAGE"
          docker tag ${{ steps.copa.outputs.patched-image }} "$FINAL_IMAGE"
          docker push "$FINAL_IMAGE"

      # 7. Create artifact name from the matrix image
      - name: Create artifact name
        id: artifact_name
        run: |
          SANITIZED_IMG=$(echo "${{ matrix.images }}" | tr '/:' '-')
          echo "artifact_name=${SANITIZED_IMG}" >> $GITHUB_OUTPUT

      # 8. Upload artifacts (Trivy report.json & cves_report.txt)
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ${{ steps.artifact_name.outputs.artifact_name }}
          path: |
            report.json
            cves_report.txt
          if-no-files-found: ignore

  merge_cves:
    runs-on: ubuntu-latest
    needs: patch 
    steps:
      - name: Download all CVE reports
        uses: actions/download-artifact@v4
        with:
          path: cve_reports/

      - name: Merge and Format CVE Reports
        run: |
          echo "### CVE Report for Release" > full_cves_report.md
          echo "" >> full_cves_report.md

          for file in $(find cve_reports -name "cves_report.txt"); do
            IMAGE_NAME=$(basename "$(dirname "$file")")  # Extract image name

            echo "## Image: $IMAGE_NAME" >> full_cves_report.md
            echo "" >> full_cves_report.md
            echo "| CVE ID | Severity | Title |" >> full_cves_report.md
            echo "|--------|----------|-------|" >> full_cves_report.md

            # Count CVEs
            CVE_COUNT=$(wc -l < "$file")
            if [[ "$CVE_COUNT" -eq 0 ]]; then
              echo "| No fixable vulnerabilities found | | |" >> full_cves_report.md
            else
              while IFS= read -r line; do
                CVE_ID=$(echo "$line" | awk -F', ' '{print $1}' | sed 's/CVE: //')
                SEVERITY=$(echo "$line" | awk -F', ' '{print $2}' | sed 's/Severity: //')
                TITLE=$(echo "$line" | awk -F', ' '{print $3}' | sed 's/Title: //')

                echo "| $CVE_ID | $SEVERITY | $TITLE |" >> full_cves_report.md
              done < "$file"
            fi

            echo "" >> full_cves_report.md  # Add spacing between images
          done

          echo "Merged CVEs Report:"
          cat full_cves_report.md

      - name: Upload Formatted CVE Report
        uses: actions/upload-artifact@v4
        with:
          name: full-cve-report
          path: full_cves_report.md

  update_release_notes:
    runs-on: ubuntu-latest
    needs: merge_cves 
    permissions:
      contents: write
    steps:
      - name: Download Merged CVE Report
        uses: actions/download-artifact@v4
        with:
          name: full-cve-report
          path: .

      - name: Authenticate with GitHub CLI
        run: echo "${{ secrets.GITHUB_TOKEN }}" | gh auth login --with-token
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Check for Existing Release
        id: get_release
        run: |
          LATEST_RELEASE=$(gh release list --limit 1 | awk '{print $1}')
          echo "LATEST_RELEASE=$LATEST_RELEASE" >> $GITHUB_ENV
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Append CVE Report to Release
        run: |
          RELEASE_TITLE="Security Patch - $(date +'%Y-%m-%d')"
          RELEASE_TAG="security-patch-$(date +'%Y-%m-%d')"

          # Fetch existing release notes
          EXISTING_NOTES=$(gh release view "$LATEST_RELEASE" --json body -q '.body' || echo "")

          # Append the new CVE report to the existing release notes
          echo "### New CVEs Added from Latest Run" > new_cves.md
          cat full_cves_report.md >> new_cves.md
          echo "" >> new_cves.md
          
          # Merge with previous release notes
          echo "$EXISTING_NOTES" > updated_notes.md
          cat new_cves.md >> updated_notes.md

          if [ -z "$LATEST_RELEASE" ]; then
            echo "No existing release found. Creating a new one..."
            gh release create "$RELEASE_TAG" \
              --title "$RELEASE_TITLE" \
              --notes-file updated_notes.md \
              --draft
          else
            echo "Updating existing release: $LATEST_RELEASE"
            gh release edit "$LATEST_RELEASE" \
              --notes-file updated_notes.md
          fi
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
