name: Generate and Commit SBOM

on:
  push:
    branches:
      - main

jobs:
  generate-and-commit-sbom:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Syft
        run: |
          curl -sSfL https://raw.githubusercontent.com/anchore/syft/main/install.sh | sh -s -- -b /usr/local/bin

      - name: Generate SBOM
        run: syft . -o cyclonedx-json=$GITHUB_REPOSITORY.json

      - name: Checkout securityCenter repository
        uses: actions/checkout@v2
        with:
          repository: bsanchezmir/securityCenter
          token: ${{ secrets.GHACTIONSECRET }}
          path: securityCenter

      - name: Copy SBOM to securityCenter repository
        run: |
          mkdir -p securityCenter/sboms/$GITHUB_REPOSITORY   # Create sboms folder if it doesn't exist
          REPO_NAME=$(basename "$GITHUB_REPOSITORY")
          SBOM_FILE=securityCenter/sboms/$GITHUB_REPOSITORY.json
          cp $GITHUB_REPOSITORY.json $SBOM_FILE

      - name: Commit and Push SBOM to securityCenter repository
        run: |
          cd securityCenter
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add sboms/$GITHUB_REPOSITORY.json
          git commit -m "Update SBOM for $GITHUB_REPOSITORY"
          git push
